import { api } from "./api"; // your base API instance

export const cartApi = api.injectEndpoints({
  endpoints: (builder) => ({
    // 👉 Get Logged-in User Cart
    getCart: builder.query({
      query: (userId: string) => `/cart/${userId}`,
      providesTags: ["Cart"],
    }),

    // 👉 Add item to cart
    addToCart: builder.mutation({
      query: (body) => ({
        url: `/cart/add`,
        method: "POST",
        body,
      }),
      invalidatesTags: ["Cart"],
    }),

    // 👉 Remove item from cart
    removeFromCart: builder.mutation({
      query: ({ productId }) => ({
        url: `/cart/remove/${productId}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Cart"],
    }),

    // 👉 Clear full cart
    clearCart: builder.mutation({
      query: () => ({
        url: `/cart/clear`,
        method: "DELETE",
      }),
      invalidatesTags: ["Cart"],
    }),
  }),
});

// Export hooks automatically generated by RTK Query
export const {
  useGetCartQuery,
  useAddToCartMutation,
  useRemoveFromCartMutation,
  useClearCartMutation,
} = cartApi;
