export const books = [
  {
    _id: "1",
    images: [],
    title: "The Alchemist",
    category: "Reading Books (Novels)",
    brand: "Anouk",
    gender: "B.Com",
    subject: "Fiction",
    price: 300,
    color: "Paulo Coelho",
    edition: "25th Anniversary Edition",
    description:
      "A philosophical book about a shepherd's journey to realize his dreams.",
    finalPrice: 250,
    shippingCharge: 50,
    paymentMode: "UPI",
    paymentDetails: {
      upiId: "example@upi",
    },
    createdAt: new Date("2024-01-01"),
    seller: { name: "John Doe", contact: "1234567890" },
  },
  {
    _id: "2",
    images: [],
    title: "7 Habits of Highly Effective People",
    category: "Reading Books (Business)",
    brand: "Anouk",
    gender: "MBA",
    subject: "Self-Help",
    price: 500,
    color: "Stephen R. Covey",
    edition: "30th Anniversary Edition",
    description: "A guide to personal and professional effectiveness.",
    finalPrice: 450,
    shippingCharge: 30,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "1234567890123456",
        ifscCode: "ABC1234567",
        bankName: "XYZ Bank",
      },
    },
    createdAt: new Date("2024-01-02"),
    seller: { name: "Jane Smith", contact: "0987654321" },
  },
  {
    _id: "3",
    images: [],
    title: "Ignited Minds",
    category: "Reading Books (Motivation)",
    brand: "Anouk",
    gender: "B.Tech",
    subject: "Inspiration",
    price: 400,
    color: "APJ Abdul Kalam",
    edition: "1st Edition",
    description: "An inspiring book aimed at the youth of India.",
    finalPrice: 350,
    shippingCharge: 40,
    paymentMode: "UPI",
    paymentDetails: {
      upiId: "kalam@upi",
    },
    createdAt: new Date("2024-01-03"),
    seller: { name: "Rahul Gupta", contact: "1122334455" },
  },
  {
    _id: "4",
    images: [],
    title: "Introduction to Algorithms",
    category: "College Books (Higher Education Textbooks)",
    brand: "Dressberry",
    gender: "M.Tech",
    subject: "Computer Science",
    price: 1200,
    color: "Thomas H. Cormen et al.",
    edition: "3rd Edition",
    description: "A comprehensive introduction to algorithms.",
    finalPrice: 1100,
    shippingCharge: 60,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "6543210987654321",
        ifscCode: "XYZ9876543",
        bankName: "ABC Bank",
      },
    },
    createdAt: new Date("2024-01-04"),
    seller: { name: "Alice Brown", contact: "2233445566" },
  },
  {
    _id: "5",
    images: [],
    title: "Data Structures and Algorithms Made Easy",
    category: "College Books (Higher Education Textbooks)",
    brand: "Dressberry",
    gender: "B.Sc",
    subject: "Computer Science",
    price: 800,
    color: "Narasimha Karumanchi",
    edition: "2nd Edition",
    description: "A comprehensive guide to data structures and algorithms.",
    finalPrice: 700,
    shippingCharge: 50,
    paymentMode: "UPI",
    paymentDetails: { upiId: "data.structures@upi" },
    createdAt: new Date("2024-01-05"),
    seller: { name: "Michael Johnson", contact: "3344556677" },
  },
  {
    _id: "6",
    images: [],
    title: "The Great Gatsby",
    category: "Reading Books (Novels)",
    brand: "Dressberry",
    gender: "12th",
    subject: "Literature",
    price: 450,
    color: "F. Scott Fitzgerald",
    edition: "New Edition",
    description: "A classic novel exploring themes of wealth and society.",
    finalPrice: 400,
    shippingCharge: 20,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "7890123456789012",
        ifscCode: "LMN4567890",
        bankName: "DEF Bank",
      },
    },
    createdAt: new Date("2024-01-06"),
    seller: { name: "Emily Davis", contact: "4455667788" },
  },
  {
    _id: "7",
    images: [],
    title: "Thinking, Fast and Slow",
    category: "Reading Books (Psychology)",
    brand: "Dressberry",
    gender: "MBA",
    subject: "Psychology",
    price: 600,
    color: "Daniel Kahneman",
    edition: "1st Edition",
    description: "An exploration of how we think and make decisions.",
    finalPrice: 550,
    shippingCharge: 25,
    paymentMode: "UPI",
    paymentDetails: { upiId: "thinking.fast@upi" },
    createdAt: new Date("2024-01-07"),
    seller: { name: "Sarah Wilson", contact: "5566778899" },
  },
  {
    _id: "8",
    images: [],
    title: "The Catcher in the Rye",
    category: "Reading Books (Novels)",
    brand: "Roadster",
    gender: "11th",
    subject: "Literature",
    price: 350,
    color: "J.D. Salinger",
    edition: "Revised Edition",
    description: "A novel about teenage rebellion and alienation.",
    finalPrice: 300,
    shippingCharge: 15,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "1234567890123456",
        ifscCode: "OPQ1234567",
        bankName: "GHI Bank",
      },
    },
    createdAt: new Date("2024-01-08"),
    seller: { name: "David Lee", contact: "6677889900" },
  },
  {
    _id: "9",
    images: [],
    title: "Becoming",
    category: "Reading Books (Biography)",
    brand: "Roadster",
    gender: "MBA",
    subject: "Biography",
    price: 500,
    color: "Michelle Obama",
    edition: "1st Edition",
    description: "The memoir of the former First Lady of the United States.",
    finalPrice: 450,
    shippingCharge: 20,
    paymentMode: "UPI",
    paymentDetails: { upiId: "becoming@upi" },
    createdAt: new Date("2024-01-09"),
    seller: { name: "Laura Green", contact: "7788990011" },
  },
  {
    _id: "10",
    images: [],
    title: "Sapiens",
    category: "Reading Books (History)",
    brand: "Roadster",
    gender: "Ph.D",
    subject: "History",
    price: 700,
    color: "Yuval Noah Harari",
    edition: "1st Edition",
    description: "A brief history of humankind.",
    finalPrice: 650,
    shippingCharge: 35,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "2345678901234567",
        ifscCode: "RST9876543",
        bankName: "JKL Bank",
      },
    },
    createdAt: new Date("2024-01-10"),
    seller: { name: "Chris Brown", contact: "8899001122" },
  },
  {
    _id: "11",
    images: [],
    title: "Sapiens",
    category: "Reading Books (History)",
    brand: "Roadster",
    gender: "Ph.D",
    subject: "History",
    price: 700,
    color: "Yuval Noah Harari",
    edition: "1st Edition",
    description: "A brief history of humankind.",
    finalPrice: 650,
    shippingCharge: 35,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "2345678901234567",
        ifscCode: "RST9876543",
        bankName: "JKL Bank",
      },
    },
    createdAt: new Date("2024-01-10"),
    seller: { name: "Chris Brown", contact: "8899001122" },
  },
  {
    _id: "12",
    images: [],
    title: "Sapiens",
    category: "Reading Books (History)",
    brand: "Roadster",
    gender: "Ph.D",
    subject: "History",
    price: 700,
    color: "Yuval Noah Harari",
    edition: "1st Edition",
    description: "A brief history of humankind.",
    finalPrice: 650,
    shippingCharge: 35,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "2345678901234567",
        ifscCode: "RST9876543",
        bankName: "JKL Bank",
      },
    },
    createdAt: new Date("2024-01-10"),
    seller: { name: "Chris Brown", contact: "8899001122" },
  },
  {
    _id: "13",
    images: [],
    title: "Sapiens",
    category: "Reading Books (History)",
    brand: "Roadster",
    gender: "Ph.D",
    subject: "History",
    price: 700,
    color: "Yuval Noah Harari",
    edition: "1st Edition",
    description: "A brief history of humankind.",
    finalPrice: 650,
    shippingCharge: 35,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "2345678901234567",
        ifscCode: "RST9876543",
        bankName: "JKL Bank",
      },
    },
    createdAt: new Date("2024-01-10"),
    seller: { name: "Chris Brown", contact: "8899001122" },
  },
  {
    _id: "14",
    images: [],
    title: "Sapiens",
    category: "Reading Books (History)",
    brand: "Roadster",
    gender: "Ph.D",
    subject: "History",
    price: 700,
    color: "Yuval Noah Harari",
    edition: "1st Edition",
    description: "A brief history of humankind.",
    finalPrice: 650,
    shippingCharge: 35,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "2345678901234567",
        ifscCode: "RST9876543",
        bankName: "JKL Bank",
      },
    },
    createdAt: new Date("2024-01-10"),
    seller: { name: "Chris Brown", contact: "8899001122" },
  },
  {
    _id: "15",
    images: [],
    title: "Sapiens",
    category: "Reading Books (History)",
    brand: "Roadster",
    gender: "Ph.D",
    subject: "History",
    price: 700,
    color: "Yuval Noah Harari",
    edition: "1st Edition",
    description: "A brief history of humankind.",
    finalPrice: 650,
    shippingCharge: 35,
    paymentMode: "Bank Account",
    paymentDetails: {
      bankDetails: {
        accountNumber: "2345678901234567",
        ifscCode: "RST9876543",
        bankName: "JKL Bank",
      },
    },
    createdAt: new Date("2024-01-10"),
    seller: { name: "Chris Brown", contact: "8899001122" },
  },
];

export const filters = {
  brand: [
    { _id: "64f8e2a7c9f1a2b3d4e5f671", name: "Anouk" },
    { _id: "64f8e2a7c9f1a2b3d4e5f672", name: "Hop" },
    { _id: "64f8e2a7c9f1a2b3d4e5f673", name: "Dressberry" },
    { _id: "64f8e2a7c9f1a2b3d4e5f674", name: "Roadster" },
    { _id: "64f8e2a7c9f1a2b3d4e5f675", name: "Suha" },
    { _id: "64f8e2a7c9f1a2b3d4e5f676", name: "Eather" },
  ],
  gender: [
    { _id: "men", name: "Men" },
    { _id: "women", name: "Women" },
    { _id: "boys", name: "Boys" },
    { _id: "girls", name: "Girls" },
    { _id: "unisex", name: "Unisex" },
  ],

  category: [
    { _id: "64f8e2a7c9f1a2b3d4e5f680", name: "Kurta" },
    { _id: "64f8e2a7c9f1a2b3d4e5f681", name: "Kurta Set" },
    { _id: "64f8e2a7c9f1a2b3d4e5f682", name: "Dupattas" },
    { _id: "64f8e2a7c9f1a2b3d4e5f683", name: "Saree" },
    { _id: "64f8e2a7c9f1a2b3d4e5f684", name: "Lehenga" },
  ],
  collection: [
    { _id: "64f8e2a7c9f1a2b3d4e5f690", name: "Festival" },
    { _id: "64f8e2a7c9f1a2b3d4e5f691", name: "Holiday" },
    { _id: "64f8e2a7c9f1a2b3d4e5f692", name: "Summer" },
    { _id: "64f8e2a7c9f1a2b3d4e5f693", name: "Occation" },
    { _id: "64f8e2a7c9f1a2b3d4e5f694", name: "All Seaeson" },
  ],
  sizes: [
    { _id: "one", name: "One" },
    { _id: "xs", name: "XS" },
    { _id: "s", name: "S" },
    { _id: "m", name: "M" },
    { _id: "l", name: "L" },
    { _id: "xl", name: "XL" },
    { _id: "2xl", name: "2XL" },
    { _id: "3xl", name: "3XL" },
    { _id: "4xl", name: "4XL" },
    { _id: "5xl", name: "5XL" },
    { _id: "6xl", name: "6XL" },
    { _id: "7xl", name: "7XL" },
    { _id: "8xl", name: "8XL" },
    { _id: "36", name: "36" },
    { _id: "38", name: "38" },
    { _id: "40", name: "40" },
    { _id: "42", name: "42" },
    { _id: "44", name: "44" },
    { _id: "46", name: "46" },
    { _id: "48", name: "48" },
    { _id: "50", name: "50" },
  ],
};

// recomended
// whats's new
// popularity
// high-to-low
// low-to-high
// customer rating
